name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install uv
      run: |
        pipx install uv
    - name: Build
      run: |
        uv build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
